### PR TITLE
updated change log, and made a note to update change log for release

### PR DESCRIPTION
**Pull request by AndrewSav**
## Description

Updated change log, and made a note to update change log for release

## Type of change

- [X] Documentation only

## Status

- [X] Ready

## Todo List
- [X] Documentation

## How has this been tested ?

This is a documentation change that will be validated via this PR peer review.

### CODE REVIEW

**Comment by AndrewSav** [comment]
@SaraSmiseth @sknight80 do we really need two change logs that are the same, one is [here](https://github.com/mailserver2/mailserver/blob/master/CHANGELOG.md) and another one is [here](https://github.com/mailserver2/mailserver/releases) ?

**Comment by SaraSmiseth** [comment]
LGTM. Yes, https://github.com/mailserver2/mailserver/releases is enough.

**Review by SaraSmiseth — APPROVED** [review]

**Comment by sknight80** [comment]
Yeah! I agree with @SaraSmiseth !

**Comment by AndrewSav** [comment]
@SaraSmiseth @sknight80 so I deleted the change log, I'll merge this then if no one minds.

**Comment by sknight80** [comment]
Go ahead!

**Pull request merged**
