### PR TITLE
Optional vhosts directory ownership setup

### PR DESCRIPTION
**Pull request by sknight80**
## Description

I added a new configuration option to avoid long restart (boot) when you have lots of mailboxes with the right ownership setup.
 
Fixes # (issue)

* What is the current behavior (you can also link to an open issue here) ? `diroots` from the Discord channel [mentioned](https://discordapp.com/channels/717500786166333561/717500786166333564/763370039826317322) that when he restarted the mail server, it took lots of time to boot up due to the high volume of mailboxes and the `find` command that set the ownership for a given folder.

* What is the new behavior (if this is a feature change)?  When we turn on the `DISABLE_VHOSTS_OWNERSHIP_SET` environment variable, the `setup.sh` will skip the `find /var/mail/vhosts` line the image will boot up faster.

## Type of change
_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] Documentation only
- [ ] Performance improvement
- [ ] Refactoring (a change that neither fixes a bug nor adds a feature)
- [ ] Test (adding missing tests or correcting existing ones)
- [ ] Other... 

## Status

- [X] Ready
- [ ] In development
- [ ] Hold

## Todo List
- [ ] Implementation
- [X] Tests
- [ ] Documentation
- [ ] ...

## How has this been tested?

Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce, and please also list any relevant details of your test configuration.

- [x] Startup the mail server without the new configuration option => The system is up and running, and the startup log does not contain `[INFO] VHOSTS directories permission set is disabled.`
- [x] Startup the mail server with the new configuration option set to true => The system is up and running, and the startup log does contain `[INFO] VHOSTS directories permission set is disabled.`
```
mailserver_1    | [INFO] VHOSTS directories permission set is disabled
mailserver_1    | [WARNING] If you manually created a directory under the vhost folder, you will not receive any emails on that email address!
```

### CODE REVIEW

**Comment by diroots** [comment]
many thanks for this @sknight80

**Comment by AndrewSav** [comment]
@sknight80 are you sure it was on discord? Cannot find any record of it ;(

**Comment by sknight80** [comment]
@AndrewSav I updated the description with the link. ;)

**Comment by AndrewSav** [comment]
I had a look at this, was trying to figure out if there is an "automatic" way to avoid the delay without the needs to specify the option, but could not come up with one, otherwise looks good. Default set - check, documentation updated check. I was a bit unsure if the default should be in run.sh or setup.sh but it looks like we have them (for other vars) in both, so I guess does not matter?

**Review by AndrewSav — APPROVED** [review]

**Review by SaraSmiseth — APPROVED** [review]

**Comment by sknight80** [comment]
I could think only for sending that one line into the background and logging back when it is done.  We could have a couple of downtime minutes to store new mails on the read-only mailboxes until the command finished it.  But honestly, when you are using the image and create a new mailbox via postfix, it should set up the right access level.  So I don't think we should run the `find` command when a new container is created.

Let us merge it and iterate on it later.

**Comment by diroots** [comment]
hello @sknight80 

i saw u did push this change to master, good to know. 
i also saw it was in the unreleased features, with some other. that means not yet available on docker hub. 

Do you know when u plan to do a new release with this feature (and the others listed) ? still some work before it goes live?

**Comment by sknight80** [comment]
Let me sync with @AndrewSav and @SaraSmiseth when do we want to release a new version

**Comment by SaraSmiseth** [comment]
I think its fine to release a new version.

What rules do we follow on when to release new versions?

**Comment by sknight80** [comment]
I think this one: https://github.com/mailserver2/mailserver/blob/master/VERSIONING.md

**Comment by SaraSmiseth** [comment]
Well it does not mention _when_ a new release will be created. What do you think about this: The person who merged something into the master branch should create a new release after that?

**Comment by sknight80** [comment]
Sounds good to me.

**Comment by AndrewSav** [comment]
Note that not all changes require a release. This one does though. So @sknight80, are you going to be doing this, in this case?

**Comment by sknight80** [comment]
Yes, today I will do it.

**Comment by sknight80** [comment]
I pushed the new version to the docker hub and added a new tag and release to GitHub.  Going to create a new PR for updating the changelog.

**Pull request merged**
