### PR TITLE
bump debian-mail-overlay image version to 1.0.1

### PR DESCRIPTION
**Pull request by sknight80**
## Description

Bump to new base image version to 1.0.1.  The base image has the latest Debian update, and all the third-party applications updated to the newest version.

## Type of change
_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] Documentation only
- [ ] Performance improvement
- [ ] Refactoring (a change that neither fixes a bug nor adds a feature)
- [ ] Test (adding missing tests or correcting existing ones)
- [X] Other... => **Version bump**

## Status

- [X] Ready
- [ ] In development
- [ ] Hold

## How has this been tested?

Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce, and please also list any relevant details of your test configuration.

- [X] Docker build command for the base image (no errors)
- [X] Run Travis for testing the new image

### CODE REVIEW

**Comment by AndrewSav** [comment]
Probably makes sense to bump image version of the mailserver in the same PR

**Review by SaraSmiseth — APPROVED** [review]
LGTM

**Comment by sknight80** [comment]
@SaraSmiseth please check the tagging that I did (versioning). I might mess up or I missed the `traefik v2` thing.

**Comment by SaraSmiseth** [comment]
The commit that is tagged [here](https://github.com/mailserver2/mailserver/releases/tag/v1.1.3) is not the correct commit. If you click on the linked [commit](https://github.com/mailserver2/mailserver/commit/93c9e3c55ac85b04e535e46a690c2d181a7e293f) there is a message: `This commit does not belong to any branch on this repository.`. [This one](https://github.com/mailserver2/mailserver/commit/ff89129421fa58a3f5e01eaca4946cd8feb1da43) is the correct commit.

**Comment by AndrewSav** [comment]
@SaraSmiseth @sknight80 I have re-tagged the lastest master and pused to dockerhub

**Pull request merged**
