### PR TITLE
fixing some more log rotation warnings

### PR DESCRIPTION
**Pull request by AndrewSav**
## Description

Fixes https://github.com/mailserver2/mailserver/issues/24

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Status

- [X] In development

## Todo List
- [X] Implementation
- [X] Testing

## How has this been tested ?

`docker-compose up -d --force-recreate` with the new image; `docker exec -it mailserver bash`, inside the container run `/usr/sbin/logrotate -f /etc/logrotate.conf`, confirm that there was no warnings.

An image is published in `andrewsav/mailserver:logrotate-1` with this change. @pollux will run it for awhile and will report their findings. Until then the PR will remain open.

### CODE REVIEW

**Comment by SaraSmiseth** [comment]
LGTM

**Review by SaraSmiseth — APPROVED** [review]

**Review by sknight80 — APPROVED** [review]
LGTM

**Comment by AndrewSav** [comment]
@SaraSmiseth @sknight80 guys I'm not sure what to do with this one. @pollux who requested it does not have time to test it: I wanted someone to run it for a few weeks and report back.

Since this is not happening, what do I do? Just close it off? Or, since the risk is not great, merge it anyway?

**Comment by pollux** [comment]
Sorry, i was and i am busy these days. But i changed to @AndrewSav image now and will report back to you.

**Comment by pollux** [comment]
I got no log rotation error mail so far. So this looks real promising. I will keep using the modified image for some additional weeks and get back to you if there is any error or i think we're fine.

**Comment by pollux** [comment]
No error until now. I guess we can merge this PR and release a new patch-version.

**Comment by AndrewSav** [comment]
@pollux noted. Thank you for testing

**Pull request merged**
