### PR TITLE
Updated base image to https://github.com/mailserver2/debian-mail-overlay/releases/tag/v1.0.13

### PR DESCRIPTION
**Pull request by AndrewSav**

### CODE REVIEW

**Comment by AndrewSav** [comment]
Apparently latest rspamd upgrade breaks the test. I do not have time to look at it this weekend, so if anyone would like to have a look, You are more than welcome

**Comment by diroots** [comment]
i think this should be set on hold, as debian did release today it's debian12.4-slim container, so if going with updated base image, it should be on this one. let me prepare it.

**Comment by diroots** [comment]
see https://github.com/mailserver2/debian-mail-overlay/pull/25 @AndrewSav

**Comment by AndrewSav** [comment]
@diroots rspamd 3.7.5 does not seem to make a difference, some one need to look at why the tests are failing

**Comment by SaraSmiseth** [comment]
I tested all rspamd versions since 3.5. Rspamd version 3.6 still works fine. Since version 3.7.1 I get the following error:

```
 ✗ checking logs: /var/log/mail.err in mailserver_default does not exist
   (from function `assert_failure' in file test/test_helper/bats-assert/src/assert.bash, line 140,
    in test file test/default.bats, line 848)
     `assert_failure' failed

   -- command succeeded, but it was expected to fail --
   output (12 lines):
     2024-01-07T07:59:01.380993+00:00 mail rspamd[1197]: <xu7gia>; cfg; rspamd_register_symbol_fromlua: duplicate symbol: CHECK_MID, skip registering
     2024-01-07T07:59:01.380999+00:00 mail rspamd[1197]: <xu7gia>; symcache; add_symbol_with_callback: trying to add virtual symbol MID_BARE_IP as real (no parent)
     2024-01-07T07:59:01.381003+00:00 mail rspamd[1197]: <xu7gia>; symcache; add_symbol_with_callback: trying to add virtual symbol MID_RHS_NOT_FQDN as real (no parent)
     2024-01-07T07:59:01.381006+00:00 mail rspamd[1197]: <xu7gia>; symcache; add_symbol_with_callback: trying to add virtual symbol MID_MISSING_BRACKETS as real (no parent)
     2024-01-07T07:59:01.381008+00:00 mail rspamd[1197]: <xu7gia>; symcache; add_symbol_with_callback: trying to add virtual symbol MID_RHS_IP_LITERAL as real (no parent)
     2024-01-07T07:59:01.381011+00:00 mail rspamd[1197]: <xu7gia>; symcache; add_symbol_with_callback: trying to add virtual symbol MID_CONTAINS_FROM as real (no parent)
     2024-01-07T07:59:01.381013+00:00 mail rspamd[1197]: <xu7gia>; symcache; add_symbol_with_callback: trying to add virtual symbol MID_RHS_MATCH_FROM as real (no parent)
     2024-01-07T07:59:01.381015+00:00 mail rspamd[1197]: <xu7gia>; symcache; add_symbol_with_callback: trying to add virtual symbol MID_RHS_MATCH_FROMTLD as real (no parent)
     2024-01-07T07:59:01.381018+00:00 mail rspamd[1197]: <xu7gia>; symcache; add_symbol_with_callback: trying to add virtual symbol MID_CONTAINS_TO as real (no parent)
     2024-01-07T07:59:01.381020+00:00 mail rspamd[1197]: <xu7gia>; symcache; add_symbol_with_callback: trying to add virtual symbol MID_RHS_MATCH_TO as real (no parent)
     2024-01-07T07:59:01.381025+00:00 mail rspamd[1197]: <xu7gia>; cfg; rspamd_register_symbol_fromlua: duplicate symbol: MID_END_EQ_FROM_USER_PART, skip registering
     2024-01-07T07:59:01.405921+00:00 mail rspamd[1197]: <xu7gia>; cfg; rspamd_init_lua_filters: init of /usr/share/rspamd/lualib/lua_ffi/spf.lua failed: /usr/share/rspamd/lualib/lua_ffi/spf.lua:71: size of C type is unknown or too large at line 35; trace: [1]:{[C]:-1 - cdef [C]}; [2]:{/usr/share/rspamd/lualib/lua_ffi/spf.lua:71 - <unknown> [main]};
   --
```

This is the only test that fails. The new rspamd version writes the above lines to mail.err and the test fails because the error log file should not exist.

It has to do something with this I think but I'm not sure what is causing it to be registered as duplicates?:
https://github.com/rspamd/rspamd/blob/e9aa6550177993b54fb168fa535bb8a881001bcc/rules/mid.lua#L82

I did not find anything in the release notes: https://rspamd.com/blog/.

**Comment by SaraSmiseth** [comment]
We could downgrade rspamd to version 3.6 in the base image to release a new version with fixes for #60. Then figure out what is causing the error logs later.
What do you think?

**Comment by AndrewSav** [comment]
I was thinking about this myself - good idea - go for it.

**Comment by AndrewSav** [comment]
@SaraSmiseth FYI @diroots silenced a few messages and the test do not fail anymore. Feel free to review <https://github.com/mailserver2/mailserver/pull/61, if you are happy with that, we can use the current rspamd

**Comment by AndrewSav** [comment]
I pushed `mailserver2/mailserver:20240109_01` to docker hub which I'm going to run for the next few days for testing

**Comment by SaraSmiseth** [comment]
> @SaraSmiseth FYI @diroots silenced a few messages and the test do not fail anymore. Feel free to review #61, if you are happy with that, we can use the current rspamd

Yes, I'm happy 😺 

> I pushed mailserver2/mailserver:20240109_01 to docker hub which I'm going to run for the next few days for testing

Thanks, I'll also run it.

**Comment by AndrewSav** [comment]
I pushed tag `20240109_01` with the [anti smuggling change](https://github.com/mailserver2/mailserver/issues/60#issuecomment-1883162483). I also changed github action checkout from v2 to v3 because v2 was severely outdated and gave a warning.

Does any one else getting this in the mailserver logs after starting the container at some stage:

```
s6-svc: fatal: unable to control /services/rsyslogd: supervisor not listening
```

**Comment by AndrewSav** [comment]
I'm happy to merge this and push 20240110_02  as latest/1.1.16, any objections?

**Comment by diroots** [comment]
[debian-mail-overlay v1.0.14](https://github.com/mailserver2/mailserver/pull/58/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R1) tag not yet created and pushed to docker registry, right?

**Comment by AndrewSav** [comment]
@diroots this PR would not build if it was not. [1.0.14](https://hub.docker.com/layers/mailserver2/debian-mail-overlay/1.0.14/images/sha256-cd26136234246a2fa423e8063a549808e129988e52dc0f2059556121fc50cee4)

**Comment by SaraSmiseth** [comment]
> I'm happy to merge this and push 20240110_02 as latest/1.1.16, any objections?

No objections. I don't see any issues with pushing it.

**Comment by AndrewSav** [comment]
Cool, I'll try and do that soon-ish

**Pull request merged**
