### PR TITLE
Update to Bookworm (mailserver2/debian-mail-overlay:1.0.12)

### PR DESCRIPTION
**Pull request by SaraSmiseth**
## Description

Update to base image mailserver2/debian-mail-overlay:1.0.12 with debian bookworm.

## Type of change

- [X] Update

## Status

- [X] Ready
- [ ] In development
- [ ] Hold

## How has this been tested?

All tests are succeeding.

### CODE REVIEW

**Comment by SaraSmiseth** [comment]
I have been using this for ~4 weeks now and everything is working fine so far.
@AndrewSav, @sknight80 Please test these changes and tell me what you think.

For some tests I had to make the sleep longer because the initialization took longer. I replaced some sleeps with while loops to wait for the port to be reachable.

**Comment by AndrewSav** [comment]
@SaraSmiseth did you push a mailserver image for that? if you did, I can pull it and use it for awhile as well.

**Comment by SaraSmiseth** [comment]
> @SaraSmiseth did you push a mailserver image for that? if you did, I can pull it and use it for awhile as well.

Yes: sarasmiseth/mailserver:testing

**Comment by AndrewSav** [comment]
Alright, I'm running on it now. May be let's check in in a week's time?

**Comment by AndrewSav** [comment]
Seems to be running here without issues.

**Comment by SaraSmiseth** [comment]
> Seems to be running here without issues.

Thanks for testing. I'll merge it and create a new release.

**Pull request merged**
